apiVersion: v1
appVersion: 3.21.2
description: Sonatype Nexus is an open source repository manager
home: https://www.sonatype.com/nexus-repository-oss
icon: http://www.sonatype.org/nexus/content/uploads/2015/06/Nexus-Logo.jpg
keywords:
- artifacts
- dependency
- management
- sonatype
- nexus
- repository
maintainers:
- email: rjkernick@gmail.com
  name: rjkernick
- email: tsiddique@live.com
  name: tsiddique
name: sonatype-nexus
sources:
- https://github.com/sonatype/nexus-public
- https://github.com/travelaudience/docker-nexus
- https://github.com/travelaudience/kubernetes-nexus
- https://github.com/travelaudience/docker-nexus-backup
version: 1.26.1
