dependencies:
- name: bootstrap-project
  version: "0.0.1"
  repository: https://rht-labs.github.io/charts
  condition: bootstrap-project.enabled
- name: argo-cd
  version: "2.0.0"
  repository: "https://tylerauerbeck.github.io/argo-helm"
  condition: argo-cd.enabled
- name: sonatype-nexus
  version: "1.26.1"
  repository: "https://oteemo.github.io/charts"
  condition: sonatype-nexus.enabled
- name: jenkins
  version: "0.0.4"
  repository: https://rht-labs.github.io/charts
  condition: jenkins.enabled