# Default values for ubiquitous-journey.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prefix: ""

ci_cd_namespace: "labs-ci-cd"
dev_namespace: "labs-dev"
test_namespace: "labs-test"

argo-cd:
  enabled: false

sonatype-nexus:
  enabled: false
