# Over rides for default values in Helm Charts
destination: &test_ns labs-test
##############
# Application Custom Values
#############
# toggle between versions of the app by setting the tag to grey / purple or latest
pet_battle: &front_end_values
  app_tag: latest
  # Could be over written in a jenkins file or your fork when doing CI/CD 
  # image_repository: image-registry.openshift-image-registry.svc:5000
  # image_name: pet-battle
  # image_namespace: labs-ci-cd
  config_map: "'http://pet-battle-api-labs-test.apps.s45.core.rht-labs.com'"

pet_battle_api: &api_values
  appName: pet-battle-api
  image_repository: quay.io
  image_name: pet-battle-api
  image_namespace: eformat
  image_version: latest

##############
# üêô Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true

##############
# Argo App of Apps declaration
#############
applications:
- name: pet-battle
  enabled: true
  source: https://github.com/springdo/pet-battle.git
  source_path: chart
  sync_policy:
    *sync_policy_true
  destination: *test_ns
  source_ref: master
  values: *front_end_values
- name: pet-battle-api
  enabled: true
  source: https://github.com/eformat/pet-battle-api.git
  source_path: chart
  sync_policy:
    *sync_policy_true
  destination: *test_ns
  source_ref: master
  values: *api_values
  ignore_differences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
    - /spec/triggers/1/imageChangeParams/lastTriggeredImage
